from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
from datetime import datetime

def create_report(prediction, confidence, file_in=None):
    pdf_filename = f"CrySense_Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    doc = SimpleDocTemplate(pdf_filename, pagesize=A4)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("CrySense AI - Baby Cry Analysis Report", styles["Title"]))
    story.append(Spacer(1, 12))
    story.append(Paragraph(f"<b>Predicted Cry Type:</b> {prediction}", styles["Normal"]))
    story.append(Spacer(1, 12))
    story.append(Paragraph(f"<b>Confidence Level:</b> {confidence:.2f}", styles["Normal"]))
    story.append(Spacer(1, 12))
    if file_in:
        story.append(Paragraph(f"<b>Audio File:</b> {file_in}", styles["Normal"]))
        story.append(Spacer(1, 12))
    story.append(Paragraph("This PDF is auto-generated by the CrySense AI system.", styles["Normal"]))
    doc.build(story)
    return pdf_filename
